version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.docker
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - local-nw
  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.docker
    working_dir: /var/www
    volumes_from:
      - app
    links:
      - app
    networks:
      - local-nw
    ports:
      - 8091:80

  node:
    image: node:alpine
    working_dir: /var/www
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/var/www
    command: sh -c "yarn && yarn run watch"

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=test_form"
      - "MYSQL_USER=test-form"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    networks:
      - local-nw
    ports:
      - "3306:3306"

  composer:
    restart: 'no'
    image: bitnami/php-fpm:7.1
    command: sh -c "composer install && php -r \"file_exists('.env') || copy('.env.example', '.env');\" && php -r \"strpos(file_get_contents('.env'), 'APP_KEY=base64:') || include('artisan');\" key:generate && php artisan migrate"
    volumes_from:
      - app
    networks:
      - local-nw
    working_dir: /var/www

  php-queue:
    restart: always
    image: bitnami/php-fpm:7.1
    command: php artisan queue:work
    volumes_from:
      - app
    networks:
      - local-nw
    working_dir: /var/www

  redis:
    image: redis:alpine
    ports:
      - "6382:6379"
    networks:
      - local-nw

networks:
  local-nw:
    driver: bridge

volumes:
  dbdata:
